<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<link href="/plugins/bootstrap/bootstrap.min.css" rel="stylesheet">
<link href="/static/css/base.css" rel="stylesheet">
<link href="/plugins/chosen/chosen.css" rel="stylesheet">
<script src="/static/js/jquery.min.js"></script>
</head>
<body id="main">
	<div class="container" id="index">
		<div class="row border-bottom">
    		  <div class="loginForm row">
    	         <div class="col-md-12 form-horizontal">
    	             <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
                        <div class="col-sm-10">
                          <input type="user_name" class="form-control" id="user_name" placeholder="用户名">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="button" class="btn btn-default" onclick="goLogin();">登录</button>
                        </div>
                      </div>
    	         </div>
    	     </div>
    	     <div class="userInfo row" style="display: none;">
        			<div class="col-md-6 border-right">
    			         <div class="row">
    			             <div class="col-md-4"><img class="headimgurl" src="" width="98%"/></div>
    			             <div class="col-md-8">
    			                 <div class="row">
    			                     <div class="col-md-6">姓名：<span class="name"></span></div>
    			                     <div class="col-md-6">等级：<span class="lvl"></span></div>
    			                 </div>
    			                 <div class="row">
    			                     <div class="col-md-6">uid：<span class="uid"></span></div>
    			                     <div class="col-md-6">VIP：<span class="vip_lvl"></span></div>
    			                 </div>
    			                 <div class="row">
    			                     <div class="col-md-6">战斗力：<span class="attack_power"></span></div>
    			                     <div class="col-md-6">性别：<span class="sex"></span></div>
    			                 </div>
    			                 <div class="row">
    			                     <div class="col-md-6">经验：<span class="exp"></span></div>
    			                     <div class="col-md-6">能量：<span class="vit"></span></div>
    			                 </div>
    			                 <div class="row">
    			                     <div class="col-md-9"><span class="h5token"></span></div>
    			                     <div class="col-md-3"><button type="button" class="editToken">修改</button></div>
    			                 </div>
    			                 <div class="row">
    			                     <div class="col-md-4"><button type="button" onclick="refreshUserInfo();">刷新信息</button></div>
    			                     <div class="col-md-4"><button type="button" onclick="exchangeCode();">兑换码</button></div>
    			                     <div class="col-md-4"><button type="button" onclick="logout();">退出</button></div>
    			                 </div>
    			             </div>
    			         </div>
        			</div>
        			<div class="col-md-6">
        			     <div class="row">
		                     <div class="col-md-4">斗币：<span class="doubi_num"></span></div>
		                     <div class="col-md-4">斗鱼币：<span class="douyu_num"></span></div>
		                     <div class="col-md-4">家财：<span class="servant_cash"></span></div>
		                 </div>
		                 <div class="row">
		                     <div class="col-md-4">威望：<span class="prestige"></span></div>
		                     <div class="col-md-4">修为池：<span class="spirit"></span></div>
		                     <div class="col-md-4">婚姻：<span class="marry_status"></span></div>
		                 </div>
                         <div class="row">
		                     <div class="col-md-4">帮派ID：<span class="fac_id"></span></div>
		                     <div class="col-md-4">帮派名称：<span class="fac_name"></span></div>
		                     <div class="col-md-4">帮派洞穴：<span class="fac_cave"></span> <button type="button" class="view_fac_cave">查看</button></div>
		                 </div>
		                 <div class="row">
                             <div class="col-md-4">排位：<span class="qualifying"></span></div>
		                     <div class="col-md-4">荣耀币：<span class="king_medal"></span></div>
		                     <div class="col-md-4">免费次数：<span class="qualifying_num"></span></div>
		                 </div>
		                 <div class="row">
                             <div class="col-md-4">历练次数：<span class="lilian_num"></span></div>
		                     <div class="col-md-4">英雄历练次数：<span class="hero_lilian_num"></span></div>
		                     <div class="col-md-4">千层塔：<span class="tower"></span> <button type="button" class="view_tower">查看</button></div>
		                 </div>
		                 <div class="row">
                             <div class="col-md-4">72变：<span class="unlock_page"></span> <button type="button" onclick="unlockPage();" class="unlockPage">解锁</button></div>
                             <div class="col-md-4">场景：<span class="unlock_scene"></span> <button type="button" onclick="unlockScene();" class="unlockScene">解锁</button></div>
		                 </div>
		                 <div class="row">
                             <div class="col-md-4">武器：<span class="unlock_weapon"></span> <button type="button" onclick="unlockWeapon();" class="unlockWeapon">解锁</button></div>
                             <div class="col-md-4">技能：<span class="unlock_skill"></span> <button type="button" onclick="unlockSkill();" class="unlockSkill">解锁</button></div>
		                 </div>
        			</div>
			</div>
		</div>
		<div class="row border-bottom config">
		<form id="configForm">
		  <table>
		      <tr>
		          <th width="100">PVP</th>
		          <td>
		              <label class="checkbox-inline">
                          <input type="checkbox" id="pvp_auto" name="pvp_auto" class="pvp_auto" value="1"> 自动战斗
                        </label>
                        <label class="checkbox-inline">
                          <input type="checkbox" id="pvp_potion" name="pvp_potion" class="pvp_potion" value="1"> 使用体力药水
                        </label>
                        <label class="checkbox-inline">
                          <input type="checkbox" id="pvp_friend_vit" name="pvp_friend_vit" class="pvp_friend_vit" value="1"> 赠送领取好友体力
                        </label>
		          </td>
		      <tr>
		      <tr>
		          <th>经脉</th>
		          <td>
		              <label class="checkbox-inline">
                      <input type="checkbox" id="meridian_auto" name="meridian_auto" class="meridian_auto" value="1"> 自动造访
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" id="meridian_flag" name="meridian_flag" class="meridian_flag" value="1"> 使用威望旗
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" id="meridian_reward" name="meridian_reward" class="meridian_reward" value="1"> 使用雪莲
                    </label>
		          </td>
		      <tr>
		      <tr>
		          <th>师徒</th>
		          <td>
		              <label class="checkbox-inline">
                          <input type="checkbox" id="master_auto" name="master_auto" class="master_auto" value="1"> 敬茶/解惑
                        </label>
		          </td>
		      <tr>
		      <tr>
		          <th>家丁</th>
		          <td>
		              <label class="checkbox-inline">
                        <input type="checkbox" id="servant_auto" name="servant_auto" class="servant_auto" value="1"> 收家财
                      </label>
                      <label class="checkbox-inline">
                        <input type="checkbox" id="servant_catch" name="servant_catch" class="servant_catch" value="1"> 捕捉
                      </label>
                      <label class="checkbox-inline">
                        <input type="checkbox" id="servant_train" name="servant_train" class="servant_train" value="1"> 训练
                      </label>
                      <label class="checkbox-inline">
                        <input type="checkbox" id="servant_rob" name="servant_rob" class="servant_rob" value="1"> 捣乱
                      </label>
                      <label class="checkbox-inline">
                        <input type="checkbox" id="servant_release" name="servant_release" class="servant_release" value="1"> 释放
                      </label>
		          </td>
		      <tr>
		      <tr>
		          <th>帮派</th>
		          <td>
		             <label class="checkbox-inline">
                      <input type="checkbox" id="faction_auto" name="faction_auto" class="faction_auto" value="1"> 捐献
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" id="faction_club" name="faction_club" class="faction_club" value="1"> 武馆
                    </label>
		          </td>
		      <tr>
		      <tr>
		          <th>王者争霸</th>
		          <td>
		             <label class="checkbox-inline">
                      <input type="checkbox" id="qualifying_person" name="qualifying_person" class="qualifying_person" value="1"> 个人
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" id="qualifying_team" name="qualifying_team" class="qualifying_team" value="1"> 团队
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" id="qualifying_doushen" name="qualifying_doushen" class="qualifying_doushen" value="1"> 斗神
                    </label>
		          </td>
		      <tr>
		      <tr>
		          <th>游历</th>
		          <td>
		             <label class="checkbox-inline">
                      <input type="checkbox" id="hangup_equip" name="hangup_equip" class="hangup_equip" value="1"> 熔炼装备
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" id="hangup_box" name="hangup_box" class="hangup_box" value="1"> 解锁宝箱
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" id="hangup_encourage" name="hangup_encourage" class="hangup_encourage" value="1"> 互动
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" id="hangup_fight" name="hangup_fight" class="hangup_fight" value="1"> 挑战
                    </label>
		          </td>
		      <tr>
		      <tr>
		          <th>历练</th>
		          <td class="form-inline">
		             <label class="checkbox-inline">
                      <input type="checkbox" id="lilian_ordinary" name="lilian_ordinary" class="lilian_ordinary" value="1"> 自动历练
                    </label>
                    <div class="form-group">
                        <select class="form-control lilian_ordinary_type" name="lilian_ordinary_type" id="lilian_ordinary_type">
                          <option value="1">爬楼</option>
                          <option value="2">经验</option>
                          <option value="3">满星</option>
                        </select>
                    </div>
                    <label class="checkbox-inline">
                      <input type="checkbox" id="lilian_used" name="lilian_used" class="lilian_used" value="1"> 使用令牌
                    </label>
		          </td>
		      <tr>
		      <tr>
		          <th>英雄历练</th>
		          <td class="form-inline">
		             <label class="checkbox-inline">
                      <input type="checkbox" id="lilian_hero_ordinary" name="lilian_hero_ordinary" class="lilian_hero_ordinary" value="1"> 自动历练
                    </label>
                    <div class="form-group">
                        <select class="form-control lilian_hero_ordinary_type" name="lilian_hero_ordinary_type" id="lilian_hero_ordinary_type">
                          <option value="1">爬楼</option>
                          <option value="2">物品</option>
                          <option value="3">满星</option>
                        </select>
                    </div>
                    <div style="display:inline-block;width:500px;">
                      <select class="lilian_hero_ordinary_goods chosen" id="lilian_hero_ordinary_goods" name="lilian_hero_ordinary_goods[]" multiple="multiple" max=4 placeholder="请选择想要获得的物品"></select>
                    </div>
		          </td>
		      <tr>
		  </table>
            <table width="100%">
                <tr>
		          <th width="100">胜点商店</th>
		          <td class="form-inline">
		             <select class="pvp_shop chosen" id="pvp_shop" name="pvp_shop[]" multiple="multiple" placeholder="请选择自动购买的商品"></select>
		          </td>
		      <tr>
		      <tr>
		          <th width="100">家财商店</th>
		          <td class="form-inline">
		             <select class="servant_shop chosen" id="servant_shop" name="servant_shop[]" multiple="multiple" placeholder="请选择自动购买的商品"></select>
		          </td>
		      <tr>
		      <tr>
		          <th width="100">王者商店</th>
		          <td class="form-inline">
		             <select class="qualifying_shop chosen" id="qualifying_shop" name="qualifying_shop[]" multiple="multiple" placeholder="请选择自动购买的商品"></select>
		          </td>
		      <tr>
            </table>
			<div class="col-md-12 text-center"><button type="button" class="btn btn-primary submitConfig">保存</button></div>
		</form>
		</div>
		<div class="row">
			<div class="logs">日志</div>
		</div>
	</div>
<script type="text/javascript" src="/plugins/chosen/chosen.jquery.js"></script>
<script type="text/javascript" src="/plugins/artDialog/dialog.js"></script>
<script src="/static/js/common.js"></script>
<script src="/static/js/index.js"></script>
<script type="text/javascript">
$('.view_tower').on('click',function(){
	dialog({
		id:'dialog',
		width:'800px',
		title: '千层塔',
		content: '加载中...',
		okValue: '刷新',
		ok: function(){
			updateTower();
			return false;
		},
		cancelValue:'关闭',
		cancel:true,
	}).show();
	updateTower();
});
$('body').on('click', '.addStatus', function(){
	var id  = $(this).data('id');
	var fun = $(this).data('fun');
	$.post("/dld/other/addStatus",{id:id},function(res){
		if(res.code == 0){
			window[fun].call();
		}else{
			alert(res.msg);
		}
	},'json');
});
$('body').on('click', '.tower-fight', function(){
	var index  = $(this).data('index');
	var floor  = $(this).data('floor');
	$.post("/dld/tower/fight",{index:index,floor:floor},function(res){
		if(res.code == 0){
			updateTower();
		}else{
			alert(res.msg);
			return false;
		}
	},'json');
});
$('body').on('click', '.status-f', function(){
	$(this).select();
});
$('body').on('click', '.saveAttrDian', function(){
	var max  = $(this).data('max');
	var sum = 0;
	var attr = {};
	$('.status-f').each(function(){
		attr[$(this).data('key')] = $(this).data('id')+':'+$(this).val();
		sum = sum + parseInt($(this).val());
	});
	if(sum > max){
		alert('属性点已超出'+(sum-max)+'点');
		return false;
	}
	$.post("/dld/tower/saveAttr",attr,function(res){
		if(res.code == 0){
			updateTower();
			alert('保存成功');
		}else{
			alert(res.msg);
		}
	},'json');
});
function updateTower()
{
	dialog({id: 'dialog'}).content('加载中...');
	$.post("/dld/tower/getInfo",function(res){
		if(res.code == 0){
			var html = '<div class="row">';
			html += '<div class="col-md-2">强命：'+res.data.status[300030].num+' <input type="text" style="width:30px;" class="status-f" data-key="qm" data-id="'+res.data.status[300030].id+'" value="'+res.data.status[300030].num+'"/></div>';
			html += '<div class="col-md-2">英勇：'+res.data.status[300031].num+' <input type="text" style="width:30px;" class="status-f" data-key="yy" data-id="'+res.data.status[300031].id+'" value="'+res.data.status[300031].num+'"/></div>';
			html += '<div class="col-md-2">坚固：'+res.data.status[300032].num+' <input type="text" style="width:30px;" class="status-f" data-key="jg" data-id="'+res.data.status[300032].id+'" value="'+res.data.status[300032].num+'"/></div>';
			html += '<div class="col-md-2">急速：'+res.data.status[300033].num+' <input type="text" style="width:30px;" class="status-f" data-key="js" data-id="'+res.data.status[300033].id+'" value="'+res.data.status[300033].num+'"/></div>';
			html += '<div class="col-md-2 '+(res.data.status[0] > 0 ? 'green' : 'gray')+'">剩余：'+res.data.status[0]+' <button type="button" class="saveAttrDian" data-max="'+res.data.maxStatus+'">确定</button></div>';
			html += '<div class="col-md-2">复活次数：'+res.data.revive+'</div>';
			html += '</div>';
			html += '<div class="row" style="margin-top:5px;">';
			for(var k in res.data.attrStatus){
				html += '<div class="col-md-2 '+(res.data.attrStatus[k].has == 1 ? 'text-success' : 'gray')+'">'+res.data.attrStatus[k].name+'：'+res.data.attrStatus[k].lv+(res.data.attrStatus[k].has == 1 && res.data.attrStatus[k].goods_num > 0 ? '' : ' <button type="button" class="addStatus" data-fun="updateTower" data-id="'+res.data.attrStatus[k].shop_id+'">开启</button>')+'</div>';
			}
			html += '</div>';
			html += '<hr>';
			html += '<div class="row">';
			for(var i in res.data.monster){
				html += '<div class="col-md-4">';
				html += '<ul class="list-unstyled '+(res.data.monster[i].status == 0 ? 'text-success' : 'gray')+'">';
				html += '<li>'+res.data.monster[i].name+'</li>';
				html += '<li>等级：'+res.data.monster[i].level+'</li>';
				for(var j in res.data.monster[i].buffList){
					html += '<li class="red">'+res.data.monster[i].buffList[j].name+'：'+res.data.monster[i].buffList[j].desc+'</li>';
				}
				html += '<li>'+(res.data.monster[i].status != 0 ? '已击败' : '<button type="button" class="tower-fight" data-index="'+res.data.monster[i].index+'" data-floor="'+res.data.floor+'">挑战</button>')+'</li>';
				html += '</ul>';
				html += '</div>';
			}
			html += '</div>';
			
		}else{
			var html = res.msg;
		}
		dialog({id: 'dialog'}).content(html);
	},'json');
}
</script>
</body>
</html>